spring.application.name=demo

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/menthfy_db}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:root}
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${MENTORSHIP_PORT:8080}
